Repository Tanzania-AI-Community/twiga, pull requests merged in 2024-10, with the labels that each got.

#33 added docs/sw folder
  docs/sw/KUANZA.md
  docs/sw/KUCHANGIA.md
  docs/sw/USANIFU.md
Labels: documentation

#37 Add UV and configure render deployment
  .all-contributorsrc
  .python-version
  Dockerfile
  README.md
  app/config.py
  app/services/messaging_service.py
  app/services/whatsapp_service.py
  app/tools/exercise/vector_database.py
  docker-compose.yml
  poetry.lock
  pyproject.toml
  uv.lock
Labels: enhancement

#42 Updates user state management and improves the onboarding flow for a smoother user experience. WIP - more changes to come.
  .gitignore
  app/database/db.py
  app/database/models.py
  app/services/messaging_service.py
  app/services/onboarding_service.py
  app/services/state_service.py
Labels: enhancement, help wanted
